name = "xeo-cf-translate-worker"
compatibility_date = "2025-06-10"
main = "worker.js"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "68facaf0ddf948009c6b6c67c109a48a"
localConnectionString = "mysql://username:password@localhost:3306/xeoos"

[vars]
AI_URL = "https://gateway.ai.cloudflare.com/v1/442fe5198bff93bdf60d4223d9618033/xeoos/google-ai-studio/v1/models/gemini-2.5-flash:generateContent"
FORUM_URL = "https://xeoos.com"

[observability.logs]
enabled = true



